//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcaClient
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:common")]
    public partial class ErrorMessageDetailType
    {
        
        private string errorMessageCdField;
        
        private string errorMessageTxtField;
        
        private string xpathContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorMessageCd
        {
            get
            {
                return this.errorMessageCdField;
            }
            set
            {
                this.errorMessageCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessageTxt
        {
            get
            {
                return this.errorMessageTxtField;
            }
            set
            {
                this.errorMessageTxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string XpathContent
        {
            get
            {
                return this.xpathContentField;
            }
            set
            {
                this.xpathContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:msg:irsacabulkrequesttransmitter")]
    public partial class ACABulkRequestTransmitterResponseType
    {
        
        private TransmissionStatusCodeType transmissionStatusCdField;
        
        private string receiptIdField;
        
        private ErrorMessageDetailType errorMessageDetailField;
        
        private string versionField;
        
        public ACABulkRequestTransmitterResponseType()
        {
            this.versionField = "1.0";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25", Order=0)]
        public TransmissionStatusCodeType TransmissionStatusCd
        {
            get
            {
                return this.transmissionStatusCdField;
            }
            set
            {
                this.transmissionStatusCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:us:gov:treasury:irs:common", Order=1)]
        public string ReceiptId
        {
            get
            {
                return this.receiptIdField;
            }
            set
            {
                this.receiptIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:us:gov:treasury:irs:common", Order=2)]
        public ErrorMessageDetailType ErrorMessageDetail
        {
            get
            {
                return this.errorMessageDetailField;
            }
            set
            {
                this.errorMessageDetailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25")]
    public enum TransmissionStatusCodeType
    {
        
        /// <remarks/>
        Accepted,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Accepted with Errors")]
        AcceptedwithErrors,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Partially Accepted")]
        PartiallyAccepted,
        
        /// <remarks/>
        Rejected,
        
        /// <remarks/>
        Processing,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("Not Found")]
        NotFound,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:msg:irsacabulkrequesttransmitter")]
    public partial class ACABulkRequestTransmitterType
    {
        
        private byte[] bulkExchangeFileField;
        
        private string versionField;
        
        public ACABulkRequestTransmitterType()
        {
            this.versionField = "1.0";
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:us:gov:treasury:irs:common", DataType="base64Binary", Order=0)]
        public byte[] BulkExchangeFile
        {
            get
            {
                return this.bulkExchangeFileField;
            }
            set
            {
                this.bulkExchangeFileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:us:gov:treasury:irs:srv:gettransmitterbulkrequest", ConfigurationName="AcaClient.BulkRequestTransmitterPortType")]
    public interface BulkRequestTransmitterPortType
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="BulkRequestTransmitter", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(AcaClient.ErrorMessageDetailType), Action="BulkRequestTransmitter", Name="ErrorMessageDetail", Namespace="urn:us:gov:treasury:irs:common")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<AcaClient.BulkRequestTransmitterResponse> BulkRequestTransmitterAsync(AcaClient.BulkRequestTransmitterRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:msg:acasecurityheader")]
    public partial class TransmitterACASecurityHeaderType
    {
        
        private string itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("UserId", Namespace="urn:us:gov:treasury:irs:common", Order=0)]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
        "")]
    public partial class SecurityHeaderType
    {
        
        private SignatureType signatureField;
        
        private TimestampType timestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
        public SignatureType Signature
        {
            get
            {
                return this.signatureField;
            }
            set
            {
                this.signatureField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xs" +
            "d")]
        public TimestampType Timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureType
    {
        
        private SignedInfoType signedInfoField;
        
        private SignatureValueType signatureValueField;
        
        private KeyInfoType keyInfoField;
        
        private ObjectType[] objectField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SignedInfoType SignedInfo
        {
            get
            {
                return this.signedInfoField;
            }
            set
            {
                this.signedInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SignatureValueType SignatureValue
        {
            get
            {
                return this.signatureValueField;
            }
            set
            {
                this.signatureValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public KeyInfoType KeyInfo
        {
            get
            {
                return this.keyInfoField;
            }
            set
            {
                this.keyInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Object", Order=3)]
        public ObjectType[] Object
        {
            get
            {
                return this.objectField;
            }
            set
            {
                this.objectField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignedInfoType
    {
        
        private CanonicalizationMethodType canonicalizationMethodField;
        
        private SignatureMethodType signatureMethodField;
        
        private ReferenceType[] referenceField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CanonicalizationMethodType CanonicalizationMethod
        {
            get
            {
                return this.canonicalizationMethodField;
            }
            set
            {
                this.canonicalizationMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SignatureMethodType SignatureMethod
        {
            get
            {
                return this.signatureMethodField;
            }
            set
            {
                this.signatureMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Reference", Order=2)]
        public ReferenceType[] Reference
        {
            get
            {
                return this.referenceField;
            }
            set
            {
                this.referenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class CanonicalizationMethodType
    {
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureMethodType
    {
        
        private string hMACOutputLengthField;
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string HMACOutputLength
        {
            get
            {
                return this.hMACOutputLengthField;
            }
            set
            {
                this.hMACOutputLengthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=1)]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ReferenceType
    {
        
        private TransformType[] transformsField;
        
        private DigestMethodType digestMethodField;
        
        private byte[] digestValueField;
        
        private string idField;
        
        private string uRIField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public TransformType[] Transforms
        {
            get
            {
                return this.transformsField;
            }
            set
            {
                this.transformsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DigestMethodType DigestMethod
        {
            get
            {
                return this.digestMethodField;
            }
            set
            {
                this.digestMethodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] DigestValue
        {
            get
            {
                return this.digestValueField;
            }
            set
            {
                this.digestValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string URI
        {
            get
            {
                return this.uRIField;
            }
            set
            {
                this.uRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class TransformType
    {
        
        private object[] itemsField;
        
        private string[] textField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("XPath", typeof(string), Order=0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DigestMethodType
    {
        
        private System.Xml.XmlNode[] anyField;
        
        private string algorithmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Algorithm
        {
            get
            {
                return this.algorithmField;
            }
            set
            {
                this.algorithmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SignatureValueType
    {
        
        private string idField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyInfoType
    {
        
        private object[] itemsField;
        
        private ItemsChoiceType2[] itemsElementNameField;
        
        private string[] textField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("KeyName", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("KeyValue", typeof(KeyValueType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("MgmtData", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PGPData", typeof(PGPDataType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RetrievalMethod", typeof(RetrievalMethodType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SPKIData", typeof(SPKIDataType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509Data", typeof(X509DataType), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType2[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class KeyValueType
    {
        
        private object itemField;
        
        private string[] textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("DSAKeyValue", typeof(DSAKeyValueType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("RSAKeyValue", typeof(RSAKeyValueType), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string[] Text
        {
            get
            {
                return this.textField;
            }
            set
            {
                this.textField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class DSAKeyValueType
    {
        
        private byte[] pField;
        
        private byte[] qField;
        
        private byte[] gField;
        
        private byte[] yField;
        
        private byte[] jField;
        
        private byte[] seedField;
        
        private byte[] pgenCounterField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] P
        {
            get
            {
                return this.pField;
            }
            set
            {
                this.pField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] Q
        {
            get
            {
                return this.qField;
            }
            set
            {
                this.qField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] G
        {
            get
            {
                return this.gField;
            }
            set
            {
                this.gField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] Y
        {
            get
            {
                return this.yField;
            }
            set
            {
                this.yField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=4)]
        public byte[] J
        {
            get
            {
                return this.jField;
            }
            set
            {
                this.jField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=5)]
        public byte[] Seed
        {
            get
            {
                return this.seedField;
            }
            set
            {
                this.seedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=6)]
        public byte[] PgenCounter
        {
            get
            {
                return this.pgenCounterField;
            }
            set
            {
                this.pgenCounterField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class RSAKeyValueType
    {
        
        private byte[] modulusField;
        
        private byte[] exponentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=0)]
        public byte[] Modulus
        {
            get
            {
                return this.modulusField;
            }
            set
            {
                this.modulusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] Exponent
        {
            get
            {
                return this.exponentField;
            }
            set
            {
                this.exponentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class PGPDataType
    {
        
        private object[] itemsField;
        
        private ItemsChoiceType1[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PGPKeyID", typeof(byte[]), DataType="base64Binary", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("PGPKeyPacket", typeof(byte[]), DataType="base64Binary", Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType1[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
    public enum ItemsChoiceType1
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        PGPKeyID,
        
        /// <remarks/>
        PGPKeyPacket,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class RetrievalMethodType
    {
        
        private TransformType[] transformsField;
        
        private string uRIField;
        
        private string typeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Transform", IsNullable=false)]
        public TransformType[] Transforms
        {
            get
            {
                return this.transformsField;
            }
            set
            {
                this.transformsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string URI
        {
            get
            {
                return this.uRIField;
            }
            set
            {
                this.uRIField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Type
        {
            get
            {
                return this.typeField;
            }
            set
            {
                this.typeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class SPKIDataType
    {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("SPKISexp", typeof(byte[]), DataType="base64Binary", Order=0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509DataType
    {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509CRL", typeof(byte[]), DataType="base64Binary", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509Certificate", typeof(byte[]), DataType="base64Binary", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509IssuerSerial", typeof(X509IssuerSerialType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509SKI", typeof(byte[]), DataType="base64Binary", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("X509SubjectName", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class X509IssuerSerialType
    {
        
        private string x509IssuerNameField;
        
        private string x509SerialNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string X509IssuerName
        {
            get
            {
                return this.x509IssuerNameField;
            }
            set
            {
                this.x509IssuerNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string X509SerialNumber
        {
            get
            {
                return this.x509SerialNumberField;
            }
            set
            {
                this.x509SerialNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
    public enum ItemsChoiceType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        X509CRL,
        
        /// <remarks/>
        X509Certificate,
        
        /// <remarks/>
        X509IssuerSerial,
        
        /// <remarks/>
        X509SKI,
        
        /// <remarks/>
        X509SubjectName,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#", IncludeInSchema=false)]
    public enum ItemsChoiceType2
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("##any:")]
        Item,
        
        /// <remarks/>
        KeyName,
        
        /// <remarks/>
        KeyValue,
        
        /// <remarks/>
        MgmtData,
        
        /// <remarks/>
        PGPData,
        
        /// <remarks/>
        RetrievalMethod,
        
        /// <remarks/>
        SPKIData,
        
        /// <remarks/>
        X509Data,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.w3.org/2000/09/xmldsig#")]
    public partial class ObjectType
    {
        
        private System.Xml.XmlNode[] anyField;
        
        private string idField;
        
        private string mimeTypeField;
        
        private string encodingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlNode[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string MimeType
        {
            get
            {
                return this.mimeTypeField;
            }
            set
            {
                this.mimeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="anyURI")]
        public string Encoding
        {
            get
            {
                return this.encodingField;
            }
            set
            {
                this.encodingField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xs" +
        "d")]
    public partial class TimestampType
    {
        
        private AttributedDateTime createdField;
        
        private AttributedDateTime expiresField;
        
        private System.Xml.XmlElement[] itemsField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public AttributedDateTime Created
        {
            get
            {
                return this.createdField;
            }
            set
            {
                this.createdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AttributedDateTime Expires
        {
            get
            {
                return this.expiresField;
            }
            set
            {
                this.expiresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=2)]
        public System.Xml.XmlElement[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xs" +
        "d")]
    public partial class AttributedDateTime
    {
        
        private string idField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, DataType="ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25")]
    public partial class ACABulkBusinessHeaderRequestType
    {
        
        private string uniqueTransmissionIdField;
        
        private System.DateTime timestampField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="token", Order=0)]
        public string UniqueTransmissionId
        {
            get
            {
                return this.uniqueTransmissionIdField;
            }
            set
            {
                this.uniqueTransmissionIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:us:gov:treasury:irs:common", Order=1)]
        public System.DateTime Timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xs" +
            "d", DataType="ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25")]
    public partial class ACATrnsmtManifestReqDtlType
    {
        
        private string paymentYrField;
        
        private DigitBooleanType priorYearDataIndField;
        
        private string eINField;
        
        private TransmissionTypeCdType transmissionTypeCdField;
        
        private string testFileCdField;
        
        private string originalReceiptIdField;
        
        private DigitBooleanType transmitterForeignEntityIndField;
        
        private bool transmitterForeignEntityIndFieldSpecified;
        
        private BusinessNameType transmitterNameGrpField;
        
        private CompanyInformationGrpType companyInformationGrpField;
        
        private VendorInformationGrpType vendorInformationGrpField;
        
        private string totalPayeeRecordCntField;
        
        private string totalPayerRecordCntField;
        
        private string softwareIdField;
        
        private FormNameType formTypeCdField;
        
        private BinaryFormatCodeType binaryFormatCdField;
        
        private string checksumAugmentationNumField;
        
        private string attachmentByteSizeNumField;
        
        private string documentSystemFileNmField;
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PaymentYr
        {
            get
            {
                return this.paymentYrField;
            }
            set
            {
                this.paymentYrField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public DigitBooleanType PriorYearDataInd
        {
            get
            {
                return this.priorYearDataIndField;
            }
            set
            {
                this.priorYearDataIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:us:gov:treasury:irs:common", Order=2)]
        public string EIN
        {
            get
            {
                return this.eINField;
            }
            set
            {
                this.eINField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public TransmissionTypeCdType TransmissionTypeCd
        {
            get
            {
                return this.transmissionTypeCdField;
            }
            set
            {
                this.transmissionTypeCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string TestFileCd
        {
            get
            {
                return this.testFileCdField;
            }
            set
            {
                this.testFileCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string OriginalReceiptId
        {
            get
            {
                return this.originalReceiptIdField;
            }
            set
            {
                this.originalReceiptIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public DigitBooleanType TransmitterForeignEntityInd
        {
            get
            {
                return this.transmitterForeignEntityIndField;
            }
            set
            {
                this.transmitterForeignEntityIndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TransmitterForeignEntityIndSpecified
        {
            get
            {
                return this.transmitterForeignEntityIndFieldSpecified;
            }
            set
            {
                this.transmitterForeignEntityIndFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public BusinessNameType TransmitterNameGrp
        {
            get
            {
                return this.transmitterNameGrpField;
            }
            set
            {
                this.transmitterNameGrpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public CompanyInformationGrpType CompanyInformationGrp
        {
            get
            {
                return this.companyInformationGrpField;
            }
            set
            {
                this.companyInformationGrpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public VendorInformationGrpType VendorInformationGrp
        {
            get
            {
                return this.vendorInformationGrpField;
            }
            set
            {
                this.vendorInformationGrpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string TotalPayeeRecordCnt
        {
            get
            {
                return this.totalPayeeRecordCntField;
            }
            set
            {
                this.totalPayeeRecordCntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string TotalPayerRecordCnt
        {
            get
            {
                return this.totalPayerRecordCntField;
            }
            set
            {
                this.totalPayerRecordCntField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string SoftwareId
        {
            get
            {
                return this.softwareIdField;
            }
            set
            {
                this.softwareIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public FormNameType FormTypeCd
        {
            get
            {
                return this.formTypeCdField;
            }
            set
            {
                this.formTypeCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:us:gov:treasury:irs:common", Order=14)]
        public BinaryFormatCodeType BinaryFormatCd
        {
            get
            {
                return this.binaryFormatCdField;
            }
            set
            {
                this.binaryFormatCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:us:gov:treasury:irs:common", Order=15)]
        public string ChecksumAugmentationNum
        {
            get
            {
                return this.checksumAugmentationNumField;
            }
            set
            {
                this.checksumAugmentationNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string AttachmentByteSizeNum
        {
            get
            {
                return this.attachmentByteSizeNumField;
            }
            set
            {
                this.attachmentByteSizeNumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string DocumentSystemFileNm
        {
            get
            {
                return this.documentSystemFileNmField;
            }
            set
            {
                this.documentSystemFileNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(Form=System.Xml.Schema.XmlSchemaForm.Qualified, Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xs" +
            "d", DataType="ID")]
        public string Id
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25")]
    public enum DigitBooleanType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("0")]
        Item0,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1")]
        Item1,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25")]
    public enum TransmissionTypeCdType
    {
        
        /// <remarks/>
        O,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        R,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25")]
    public partial class BusinessNameType
    {
        
        private string businessNameLine1TxtField;
        
        private string businessNameLine2TxtField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BusinessNameLine1Txt
        {
            get
            {
                return this.businessNameLine1TxtField;
            }
            set
            {
                this.businessNameLine1TxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string BusinessNameLine2Txt
        {
            get
            {
                return this.businessNameLine2TxtField;
            }
            set
            {
                this.businessNameLine2TxtField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25")]
    public partial class CompanyInformationGrpType
    {
        
        private string companyNmField;
        
        private BusinessAddressGrpType mailingAddressGrpField;
        
        private OtherCompletePersonNameType contactNameGrpField;
        
        private string contactPhoneNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CompanyNm
        {
            get
            {
                return this.companyNmField;
            }
            set
            {
                this.companyNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public BusinessAddressGrpType MailingAddressGrp
        {
            get
            {
                return this.mailingAddressGrpField;
            }
            set
            {
                this.mailingAddressGrpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public OtherCompletePersonNameType ContactNameGrp
        {
            get
            {
                return this.contactNameGrpField;
            }
            set
            {
                this.contactNameGrpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ContactPhoneNum
        {
            get
            {
                return this.contactPhoneNumField;
            }
            set
            {
                this.contactPhoneNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25")]
    public partial class BusinessAddressGrpType
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ForeignAddressGrp", typeof(ForeignAddressGrpType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("USAddressGrp", typeof(USAddressGrpType), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25")]
    public partial class ForeignAddressGrpType
    {
        
        private string addressLine1TxtField;
        
        private string addressLine2TxtField;
        
        private string cityNmField;
        
        private object itemField;
        
        private string foreignProvinceNmField;
        
        private string foreignPostalCdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AddressLine1Txt
        {
            get
            {
                return this.addressLine1TxtField;
            }
            set
            {
                this.addressLine1TxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AddressLine2Txt
        {
            get
            {
                return this.addressLine2TxtField;
            }
            set
            {
                this.addressLine2TxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:us:gov:treasury:irs:common", Order=2)]
        public string CityNm
        {
            get
            {
                return this.cityNmField;
            }
            set
            {
                this.cityNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CountryCd", typeof(CountryType), Order=3)]
        [System.Xml.Serialization.XmlElementAttribute("CountryNm", typeof(string), Order=3)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ForeignProvinceNm
        {
            get
            {
                return this.foreignProvinceNmField;
            }
            set
            {
                this.foreignProvinceNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ForeignPostalCd
        {
            get
            {
                return this.foreignPostalCdField;
            }
            set
            {
                this.foreignPostalCdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25")]
    public enum CountryType
    {
        
        /// <remarks/>
        AF,
        
        /// <remarks/>
        AX,
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        AG,
        
        /// <remarks/>
        AQ,
        
        /// <remarks/>
        AN,
        
        /// <remarks/>
        AO,
        
        /// <remarks/>
        AV,
        
        /// <remarks/>
        AY,
        
        /// <remarks/>
        AC,
        
        /// <remarks/>
        AR,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        AA,
        
        /// <remarks/>
        AT,
        
        /// <remarks/>
        AS,
        
        /// <remarks/>
        AU,
        
        /// <remarks/>
        AJ,
        
        /// <remarks/>
        BF,
        
        /// <remarks/>
        BA,
        
        /// <remarks/>
        FQ,
        
        /// <remarks/>
        BG,
        
        /// <remarks/>
        BB,
        
        /// <remarks/>
        BO,
        
        /// <remarks/>
        BE,
        
        /// <remarks/>
        BH,
        
        /// <remarks/>
        BN,
        
        /// <remarks/>
        BD,
        
        /// <remarks/>
        BT,
        
        /// <remarks/>
        BL,
        
        /// <remarks/>
        BK,
        
        /// <remarks/>
        BC,
        
        /// <remarks/>
        BV,
        
        /// <remarks/>
        BR,
        
        /// <remarks/>
        IO,
        
        /// <remarks/>
        VI,
        
        /// <remarks/>
        BX,
        
        /// <remarks/>
        BU,
        
        /// <remarks/>
        UV,
        
        /// <remarks/>
        BM,
        
        /// <remarks/>
        BY,
        
        /// <remarks/>
        CB,
        
        /// <remarks/>
        CM,
        
        /// <remarks/>
        CA,
        
        /// <remarks/>
        CV,
        
        /// <remarks/>
        CJ,
        
        /// <remarks/>
        CT,
        
        /// <remarks/>
        CD,
        
        /// <remarks/>
        CI,
        
        /// <remarks/>
        CH,
        
        /// <remarks/>
        KT,
        
        /// <remarks/>
        IP,
        
        /// <remarks/>
        CK,
        
        /// <remarks/>
        CO,
        
        /// <remarks/>
        CN,
        
        /// <remarks/>
        CF,
        
        /// <remarks/>
        CG,
        
        /// <remarks/>
        CW,
        
        /// <remarks/>
        CR,
        
        /// <remarks/>
        CS,
        
        /// <remarks/>
        IV,
        
        /// <remarks/>
        HR,
        
        /// <remarks/>
        CU,
        
        /// <remarks/>
        UC,
        
        /// <remarks/>
        CY,
        
        /// <remarks/>
        EZ,
        
        /// <remarks/>
        DA,
        
        /// <remarks/>
        DX,
        
        /// <remarks/>
        DJ,
        
        /// <remarks/>
        DO,
        
        /// <remarks/>
        DR,
        
        /// <remarks/>
        TT,
        
        /// <remarks/>
        EC,
        
        /// <remarks/>
        EG,
        
        /// <remarks/>
        ES,
        
        /// <remarks/>
        EK,
        
        /// <remarks/>
        ER,
        
        /// <remarks/>
        EN,
        
        /// <remarks/>
        ET,
        
        /// <remarks/>
        FK,
        
        /// <remarks/>
        FO,
        
        /// <remarks/>
        FM,
        
        /// <remarks/>
        FJ,
        
        /// <remarks/>
        FI,
        
        /// <remarks/>
        FR,
        
        /// <remarks/>
        FP,
        
        /// <remarks/>
        FS,
        
        /// <remarks/>
        GB,
        
        /// <remarks/>
        GA,
        
        /// <remarks/>
        GG,
        
        /// <remarks/>
        GM,
        
        /// <remarks/>
        GH,
        
        /// <remarks/>
        GI,
        
        /// <remarks/>
        GR,
        
        /// <remarks/>
        GL,
        
        /// <remarks/>
        GJ,
        
        /// <remarks/>
        GQ,
        
        /// <remarks/>
        GT,
        
        /// <remarks/>
        GK,
        
        /// <remarks/>
        GV,
        
        /// <remarks/>
        PU,
        
        /// <remarks/>
        GY,
        
        /// <remarks/>
        HA,
        
        /// <remarks/>
        HM,
        
        /// <remarks/>
        VT,
        
        /// <remarks/>
        HO,
        
        /// <remarks/>
        HK,
        
        /// <remarks/>
        HQ,
        
        /// <remarks/>
        HU,
        
        /// <remarks/>
        IC,
        
        /// <remarks/>
        IN,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        IR,
        
        /// <remarks/>
        IZ,
        
        /// <remarks/>
        EI,
        
        /// <remarks/>
        IS,
        
        /// <remarks/>
        IT,
        
        /// <remarks/>
        JM,
        
        /// <remarks/>
        JN,
        
        /// <remarks/>
        JA,
        
        /// <remarks/>
        DQ,
        
        /// <remarks/>
        JE,
        
        /// <remarks/>
        JQ,
        
        /// <remarks/>
        JO,
        
        /// <remarks/>
        KZ,
        
        /// <remarks/>
        KE,
        
        /// <remarks/>
        KQ,
        
        /// <remarks/>
        KR,
        
        /// <remarks/>
        KN,
        
        /// <remarks/>
        KS,
        
        /// <remarks/>
        KV,
        
        /// <remarks/>
        KU,
        
        /// <remarks/>
        KG,
        
        /// <remarks/>
        LA,
        
        /// <remarks/>
        LG,
        
        /// <remarks/>
        LE,
        
        /// <remarks/>
        LT,
        
        /// <remarks/>
        LI,
        
        /// <remarks/>
        LY,
        
        /// <remarks/>
        LS,
        
        /// <remarks/>
        LH,
        
        /// <remarks/>
        LU,
        
        /// <remarks/>
        MC,
        
        /// <remarks/>
        MK,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        MI,
        
        /// <remarks/>
        MY,
        
        /// <remarks/>
        MV,
        
        /// <remarks/>
        ML,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        IM,
        
        /// <remarks/>
        RM,
        
        /// <remarks/>
        MR,
        
        /// <remarks/>
        MP,
        
        /// <remarks/>
        MX,
        
        /// <remarks/>
        MQ,
        
        /// <remarks/>
        MD,
        
        /// <remarks/>
        MN,
        
        /// <remarks/>
        MG,
        
        /// <remarks/>
        MJ,
        
        /// <remarks/>
        MH,
        
        /// <remarks/>
        MO,
        
        /// <remarks/>
        MZ,
        
        /// <remarks/>
        WA,
        
        /// <remarks/>
        NR,
        
        /// <remarks/>
        BQ,
        
        /// <remarks/>
        NP,
        
        /// <remarks/>
        NL,
        
        /// <remarks/>
        NC,
        
        /// <remarks/>
        NZ,
        
        /// <remarks/>
        NU,
        
        /// <remarks/>
        NG,
        
        /// <remarks/>
        NI,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        NF,
        
        /// <remarks/>
        CQ,
        
        /// <remarks/>
        NO,
        
        /// <remarks/>
        MU,
        
        /// <remarks/>
        OC,
        
        /// <remarks/>
        PK,
        
        /// <remarks/>
        PS,
        
        /// <remarks/>
        LQ,
        
        /// <remarks/>
        PM,
        
        /// <remarks/>
        PP,
        
        /// <remarks/>
        PF,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PE,
        
        /// <remarks/>
        RP,
        
        /// <remarks/>
        PC,
        
        /// <remarks/>
        PL,
        
        /// <remarks/>
        PO,
        
        /// <remarks/>
        RQ,
        
        /// <remarks/>
        QA,
        
        /// <remarks/>
        RO,
        
        /// <remarks/>
        RS,
        
        /// <remarks/>
        RW,
        
        /// <remarks/>
        TB,
        
        /// <remarks/>
        RN,
        
        /// <remarks/>
        WS,
        
        /// <remarks/>
        SM,
        
        /// <remarks/>
        TP,
        
        /// <remarks/>
        SA,
        
        /// <remarks/>
        SG,
        
        /// <remarks/>
        RI,
        
        /// <remarks/>
        SE,
        
        /// <remarks/>
        SL,
        
        /// <remarks/>
        SN,
        
        /// <remarks/>
        NN,
        
        /// <remarks/>
        LO,
        
        /// <remarks/>
        SI,
        
        /// <remarks/>
        BP,
        
        /// <remarks/>
        SO,
        
        /// <remarks/>
        SF,
        
        /// <remarks/>
        SX,
        
        /// <remarks/>
        OD,
        
        /// <remarks/>
        SP,
        
        /// <remarks/>
        PG,
        
        /// <remarks/>
        CE,
        
        /// <remarks/>
        SH,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        ST,
        
        /// <remarks/>
        SB,
        
        /// <remarks/>
        VC,
        
        /// <remarks/>
        SU,
        
        /// <remarks/>
        NS,
        
        /// <remarks/>
        SV,
        
        /// <remarks/>
        WZ,
        
        /// <remarks/>
        SW,
        
        /// <remarks/>
        SZ,
        
        /// <remarks/>
        SY,
        
        /// <remarks/>
        TW,
        
        /// <remarks/>
        TI,
        
        /// <remarks/>
        TZ,
        
        /// <remarks/>
        TH,
        
        /// <remarks/>
        TO,
        
        /// <remarks/>
        TL,
        
        /// <remarks/>
        TN,
        
        /// <remarks/>
        TD,
        
        /// <remarks/>
        TS,
        
        /// <remarks/>
        TU,
        
        /// <remarks/>
        TX,
        
        /// <remarks/>
        TK,
        
        /// <remarks/>
        TV,
        
        /// <remarks/>
        UG,
        
        /// <remarks/>
        UP,
        
        /// <remarks/>
        AE,
        
        /// <remarks/>
        UK,
        
        /// <remarks/>
        UY,
        
        /// <remarks/>
        UZ,
        
        /// <remarks/>
        NH,
        
        /// <remarks/>
        VE,
        
        /// <remarks/>
        VM,
        
        /// <remarks/>
        VQ,
        
        /// <remarks/>
        WQ,
        
        /// <remarks/>
        WF,
        
        /// <remarks/>
        WI,
        
        /// <remarks/>
        YM,
        
        /// <remarks/>
        ZA,
        
        /// <remarks/>
        ZI,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25")]
    public partial class USAddressGrpType
    {
        
        private string addressLine1TxtField;
        
        private string addressLine2TxtField;
        
        private string cityNmField;
        
        private StateType uSStateCdField;
        
        private string uSZIPCdField;
        
        private string uSZIPExtensionCdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AddressLine1Txt
        {
            get
            {
                return this.addressLine1TxtField;
            }
            set
            {
                this.addressLine1TxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AddressLine2Txt
        {
            get
            {
                return this.addressLine2TxtField;
            }
            set
            {
                this.addressLine2TxtField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:us:gov:treasury:irs:common", Order=2)]
        public string CityNm
        {
            get
            {
                return this.cityNmField;
            }
            set
            {
                this.cityNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public StateType USStateCd
        {
            get
            {
                return this.uSStateCdField;
            }
            set
            {
                this.uSStateCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:us:gov:treasury:irs:common", Order=4)]
        public string USZIPCd
        {
            get
            {
                return this.uSZIPCdField;
            }
            set
            {
                this.uSZIPCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="urn:us:gov:treasury:irs:common", Order=5)]
        public string USZIPExtensionCd
        {
            get
            {
                return this.uSZIPExtensionCdField;
            }
            set
            {
                this.uSZIPExtensionCdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25")]
    public enum StateType
    {
        
        /// <remarks/>
        AL,
        
        /// <remarks/>
        AK,
        
        /// <remarks/>
        AS,
        
        /// <remarks/>
        AZ,
        
        /// <remarks/>
        AR,
        
        /// <remarks/>
        CA,
        
        /// <remarks/>
        CO,
        
        /// <remarks/>
        MP,
        
        /// <remarks/>
        CT,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        DC,
        
        /// <remarks/>
        FM,
        
        /// <remarks/>
        FL,
        
        /// <remarks/>
        GA,
        
        /// <remarks/>
        GU,
        
        /// <remarks/>
        HI,
        
        /// <remarks/>
        ID,
        
        /// <remarks/>
        IL,
        
        /// <remarks/>
        IN,
        
        /// <remarks/>
        IA,
        
        /// <remarks/>
        KS,
        
        /// <remarks/>
        KY,
        
        /// <remarks/>
        LA,
        
        /// <remarks/>
        ME,
        
        /// <remarks/>
        MH,
        
        /// <remarks/>
        MD,
        
        /// <remarks/>
        MA,
        
        /// <remarks/>
        MI,
        
        /// <remarks/>
        MN,
        
        /// <remarks/>
        MS,
        
        /// <remarks/>
        MO,
        
        /// <remarks/>
        MT,
        
        /// <remarks/>
        NE,
        
        /// <remarks/>
        NV,
        
        /// <remarks/>
        NH,
        
        /// <remarks/>
        NJ,
        
        /// <remarks/>
        NM,
        
        /// <remarks/>
        NY,
        
        /// <remarks/>
        NC,
        
        /// <remarks/>
        ND,
        
        /// <remarks/>
        OH,
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        OR,
        
        /// <remarks/>
        PW,
        
        /// <remarks/>
        PA,
        
        /// <remarks/>
        PR,
        
        /// <remarks/>
        RI,
        
        /// <remarks/>
        SC,
        
        /// <remarks/>
        SD,
        
        /// <remarks/>
        TN,
        
        /// <remarks/>
        TX,
        
        /// <remarks/>
        VI,
        
        /// <remarks/>
        UT,
        
        /// <remarks/>
        VT,
        
        /// <remarks/>
        VA,
        
        /// <remarks/>
        WA,
        
        /// <remarks/>
        WV,
        
        /// <remarks/>
        WI,
        
        /// <remarks/>
        WY,
        
        /// <remarks/>
        AA,
        
        /// <remarks/>
        AE,
        
        /// <remarks/>
        AP,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25")]
    public partial class OtherCompletePersonNameType
    {
        
        private string personFirstNmField;
        
        private string personMiddleNmField;
        
        private string personLastNmField;
        
        private string suffixNmField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string PersonFirstNm
        {
            get
            {
                return this.personFirstNmField;
            }
            set
            {
                this.personFirstNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string PersonMiddleNm
        {
            get
            {
                return this.personMiddleNmField;
            }
            set
            {
                this.personMiddleNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string PersonLastNm
        {
            get
            {
                return this.personLastNmField;
            }
            set
            {
                this.personLastNmField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SuffixNm
        {
            get
            {
                return this.suffixNmField;
            }
            set
            {
                this.suffixNmField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25")]
    public partial class VendorInformationGrpType
    {
        
        private string vendorCdField;
        
        private OtherCompletePersonNameType contactNameGrpField;
        
        private string contactPhoneNumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string VendorCd
        {
            get
            {
                return this.vendorCdField;
            }
            set
            {
                this.vendorCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public OtherCompletePersonNameType ContactNameGrp
        {
            get
            {
                return this.contactNameGrpField;
            }
            set
            {
                this.contactNameGrpField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ContactPhoneNum
        {
            get
            {
                return this.contactPhoneNumField;
            }
            set
            {
                this.contactPhoneNumField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25")]
    public enum FormNameType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1094/1095B")]
        Item10941095B,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("1094/1095C")]
        Item10941095C,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:us:gov:treasury:irs:common")]
    public enum BinaryFormatCodeType
    {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("application/xml")]
        applicationxml,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BulkRequestTransmitterRequest
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:us:gov:treasury:irs:msg:acasecurityheader")]
        public AcaClient.TransmitterACASecurityHeaderType ACASecurityHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" +
            "")]
        public AcaClient.SecurityHeaderType Security;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:us:gov:treasury:irs:msg:acabusinessheader")]
        public AcaClient.ACABulkBusinessHeaderRequestType ACABusinessHeader;
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:us:gov:treasury:irs:ext:aca:air:ty25")]
        public AcaClient.ACATrnsmtManifestReqDtlType ACATransmitterManifestReqDtl;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:us:gov:treasury:irs:msg:irsacabulkrequesttransmitter", Order=0)]
        public AcaClient.ACABulkRequestTransmitterType ACABulkRequestTransmitter;
        
        public BulkRequestTransmitterRequest()
        {
        }
        
        public BulkRequestTransmitterRequest(AcaClient.TransmitterACASecurityHeaderType ACASecurityHeader, AcaClient.SecurityHeaderType Security, AcaClient.ACABulkBusinessHeaderRequestType ACABusinessHeader, AcaClient.ACATrnsmtManifestReqDtlType ACATransmitterManifestReqDtl, AcaClient.ACABulkRequestTransmitterType ACABulkRequestTransmitter)
        {
            this.ACASecurityHeader = ACASecurityHeader;
            this.Security = Security;
            this.ACABusinessHeader = ACABusinessHeader;
            this.ACATransmitterManifestReqDtl = ACATransmitterManifestReqDtl;
            this.ACABulkRequestTransmitter = ACABulkRequestTransmitter;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class BulkRequestTransmitterResponse
    {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="urn:us:gov:treasury:irs:msg:acabusinessheader")]
        public AcaClient.ACABulkBusinessHeaderRequestType ACABusinessHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn:us:gov:treasury:irs:msg:irsacabulkrequesttransmitter", Order=0)]
        public AcaClient.ACABulkRequestTransmitterResponseType ACABulkRequestTransmitterResponse;
        
        public BulkRequestTransmitterResponse()
        {
        }
        
        public BulkRequestTransmitterResponse(AcaClient.ACABulkBusinessHeaderRequestType ACABusinessHeader, AcaClient.ACABulkRequestTransmitterResponseType ACABulkRequestTransmitterResponse)
        {
            this.ACABusinessHeader = ACABusinessHeader;
            this.ACABulkRequestTransmitterResponse = ACABulkRequestTransmitterResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface BulkRequestTransmitterPortTypeChannel : AcaClient.BulkRequestTransmitterPortType, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class BulkRequestTransmitterPortTypeClient : System.ServiceModel.ClientBase<AcaClient.BulkRequestTransmitterPortType>, AcaClient.BulkRequestTransmitterPortType
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public BulkRequestTransmitterPortTypeClient() : 
                base(BulkRequestTransmitterPortTypeClient.GetDefaultBinding(), BulkRequestTransmitterPortTypeClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BulkRequestTransmitterPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BulkRequestTransmitterPortTypeClient(EndpointConfiguration endpointConfiguration) : 
                base(BulkRequestTransmitterPortTypeClient.GetBindingForEndpoint(endpointConfiguration), BulkRequestTransmitterPortTypeClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BulkRequestTransmitterPortTypeClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(BulkRequestTransmitterPortTypeClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BulkRequestTransmitterPortTypeClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(BulkRequestTransmitterPortTypeClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public BulkRequestTransmitterPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AcaClient.BulkRequestTransmitterResponse> AcaClient.BulkRequestTransmitterPortType.BulkRequestTransmitterAsync(AcaClient.BulkRequestTransmitterRequest request)
        {
            return base.Channel.BulkRequestTransmitterAsync(request);
        }
        
        public System.Threading.Tasks.Task<AcaClient.BulkRequestTransmitterResponse> BulkRequestTransmitterAsync(AcaClient.TransmitterACASecurityHeaderType ACASecurityHeader, AcaClient.SecurityHeaderType Security, AcaClient.ACABulkBusinessHeaderRequestType ACABusinessHeader, AcaClient.ACATrnsmtManifestReqDtlType ACATransmitterManifestReqDtl, AcaClient.ACABulkRequestTransmitterType ACABulkRequestTransmitter)
        {
            AcaClient.BulkRequestTransmitterRequest inValue = new AcaClient.BulkRequestTransmitterRequest();
            inValue.ACASecurityHeader = ACASecurityHeader;
            inValue.Security = Security;
            inValue.ACABusinessHeader = ACABusinessHeader;
            inValue.ACATransmitterManifestReqDtl = ACATransmitterManifestReqDtl;
            inValue.ACABulkRequestTransmitter = ACABulkRequestTransmitter;
            return ((AcaClient.BulkRequestTransmitterPortType)(this)).BulkRequestTransmitterAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BulkRequestTransmitterPort))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap11, System.ServiceModel.Channels.AddressingVersion.WSAddressing10);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BulkRequestTransmitterPort))
            {
                return new System.ServiceModel.EndpointAddress("https://la.www4.irs.gov/airp/aca/a2a/1095BC_Transmission_AATS");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return BulkRequestTransmitterPortTypeClient.GetBindingForEndpoint(EndpointConfiguration.BulkRequestTransmitterPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return BulkRequestTransmitterPortTypeClient.GetEndpointAddress(EndpointConfiguration.BulkRequestTransmitterPort);
        }
        
        public enum EndpointConfiguration
        {
            
            BulkRequestTransmitterPort,
        }
    }
}
